
export { Slider1 as ScreenSlider1 } from "./Slider1"
export { Slider2 as ScreenSlider2 } from "./Slider2"
export { Slider3 as ScreenSlider3 } from "./Slider3"
export { Slider4 as ScreenSlider4 } from "./Slider4"
export { Login as ScreenLogin } from "./Login"
export { Cadastro as ScreenCadastro } from "./Cadastro" 
export {Perfil as ScreenPerfil} from "./Perfil"
export {CameraScreen as ScreenCamera} from "./Camera"
export {LocationScreen as ScreenLocation } from "./Location"